#!/bin/sh -e
#
# /etc/init.d/ThermoApp
# description: ThermoApp application
#
# processname: Variscite


for pin in 144 146 161 164
do
if [ ! -d "/sys/class/gpio/gpio$pin" ];
then
echo $pin > /sys/class/gpio/export
fi
done
#echo out > /sys/class/gpio/gpio43/direction
echo out > /sys/class/gpio/gpio144/direction
echo out > /sys/class/gpio/gpio161/direction
echo out > /sys/class/gpio/gpio164/direction
echo 1 > /sys/class/gpio/gpio161/value

#Set 3G module role as host                                 
if [ -d "/sys/kernel/debug/ci_hdrc.0" ];
then
echo host > /sys/kernel/debug/ci_hdrc.0/role                
fi
                                                            
# Reset the gsm pin to detect the 3G module                 
#echo 1 > /sys/class/leds/gsminit/brightness        

                                                            
# export the input config             
export TSLIB_TSDEVICE=/dev/input/event1
export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/event1
if [ ! -f "/dev/input/event1" ];                            
then                                                        
export TSLIB_TSDEVICE=/dev/input/event0                     
export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/event0
fi                                       

echo -e '\033[9;0]' > /dev/tty1
echo 0 > /sys/class/graphics/fbcon/cursor_blink
echo 0 > /sys/class/graphics/fb0/blank
export TSLIB_CALIBFILE=/etc/pointercal
export TSLIB_CONFFILE=/etc/ts.conf
export QT_QPA_PLATFORM=linuxfb:fb=/dev/fb0:size=1024x600:mmSize=1024x600
export QT_QPA_EGLFS_WIDTH=1024
export QT_QPA_EGLFS_HEIGHT=600
export TSLIB_TSEVENTTYPE='INPUT'

export TERM=linux
setterm -blank 0 > /dev/tty0

#Check For FirstBoot 
if [ ! -f "/run/media/mmcblk0p1/.formatted" ];                               
then                                                                    
        if [ -d "/run/media/mmcblk0p1" ];                               
        then                                                            
                umount -f /run/media/mmcblk0p1                          
        fi                                                              
        echo "********** Preparing the eMMC DATA partition for first time use ******************"   
	clear > /dev/tty0
        echo "********** Preparing the eMMC DATA partition for first time use ******************"  > /dev/tty0 
        dd if=/dev/urandom of=/dev/mmcblk0 bs=1M count=32               
fdisk /dev/mmcblk0 <<EOF
n
p
1


w
EOF
        sleep 1                                                      
        mkfs.ext4 /dev/mmcblk0p1                                     
        sleep 1                                                      
        /etc/init.d/udev restart                                     
sleep 2                            
echo done > /run/media/mmcblk0p1/.formatted
sync

echo "******** Erasing  NAND  *****************"
	clear > /dev/tty0
echo "******** Erasing  NAND  *****************" > /dev/tty0
flash_erase /dev/mtd0 0 0
flash_erase /dev/mtd1 0 0
flash_erase /dev/mtd2 0 0
flash_erase /dev/mtd3 0 0
flash_erase /dev/mtd4 0 0
flash_erase /dev/mtd5 0 0
flash_erase /dev/mtd6 0 0
flash_erase /dev/mtd7 0 0
sleep 1
sync
sync
echo "******** Writing the Software to NAND *****************"
	clear > /dev/tty0
echo "******** Writing the Software to NAND *****************" > /dev/tty0
kobs-ng init -x /run/media/mmcblk1p3/SPL-nand  --search_exponent=1 -v
nandwrite -p /dev/mtd1 /run/media/mmcblk1p3/u-boot.img 
nandwrite -p /dev/mtd3 /run/media/mmcblk1p3/u-boot.img 
nandwrite -p /dev/mtd4 /run/media/mmcblk1p3/uImage-imx6q-var-som-cap.dtb
nandwrite -p /dev/mtd5 /run/media/mmcblk1p3/uImage
ubiformat /dev/mtd7 -f /run/media/mmcblk1p3/tfs-image-rootfs-var-som-mx6.ubi -s 2048 -O 2048
sync

echo " ******** Please reboot to Boot from NAND ***********"
	clear > /dev/tty0
echo " ******** Please remove J28 and reset to Boot from NAND ***********" > /dev/tty0
sync
sync
fi                             

sync
exit $RETVAL                 
